# Copyright 2025 Matheus Pimenta.
# SPDX-License-Identifier: AGPL-3.0

inputs:
  google-service-account-name:
    required: true
  github-token:
    required: true

runs:
  using: composite
  steps:
  - name: Free disk space
    shell: bash
    run: |
      set -eux
      df -h
      sudo rm -rf /usr/share/dotnet || true
      sudo rm -rf /opt/ghc || true
      sudo rm -rf /usr/local/share/boost || true
      sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
      sudo rm -rf /usr/local/lib/android || true
      docker system prune -af || true
      sudo apt-get clean || true
      df -h
  - uses: stefanprodan/timoni/actions/setup@main
  - uses: google-github-actions/auth@v3
    with:
      project_id: gke-metadata-server
      workload_identity_provider: projects/637293746831/locations/global/workloadIdentityPools/github-actions/providers/github-actions
      service_account: ${{ inputs.google-service-account-name }}@gke-metadata-server.iam.gserviceaccount.com
  - uses: docker/login-action@v3
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ inputs.github-token }}
  - uses: docker/setup-qemu-action@v3
  - uses: docker/setup-buildx-action@v3
  - name: Install dependencies
    shell: bash
    run: |
      sudo apt-get update && sudo apt-get install -y clang llvm bpfcc-tools libbpf-dev linux-tools-azure
