# Copyright 2025 Matheus Pimenta.
# SPDX-License-Identifier: AGPL-3.0

inputs:
  component:
    required: true
  source-repository:
    required: true
  target-repository:
    required: true
  version:
    required: true
  latest:
    required: false

outputs:
  image-with-digest:
    value: ${{ steps.copy.outputs.image-with-digest }}

runs:
  using: composite
  steps:
  - id: copy
    shell: bash
    env:
      COMPONENT: ${{ inputs.component }}
      SOURCE_REPOSITORY: ${{ inputs.source-repository }}
      TARGET_REPOSITORY: ${{ inputs.target-repository }}
      VERSION: ${{ inputs.version }}
      LATEST: ${{ inputs.latest }}
    run: |
      digest=$(cat ${COMPONENT}-digest.txt)
      src=ghcr.io/matheuscscp/gke-metadata-server/${SOURCE_REPOSITORY}@${digest}
      dst=ghcr.io/matheuscscp/${TARGET_REPOSITORY}@${digest}
      skopeo copy --all docker://$src docker://$dst
      skopeo copy --all docker://$dst docker://ghcr.io/matheuscscp/${TARGET_REPOSITORY}:${VERSION}
      if [ "$LATEST" != "skip" ]; then
        skopeo copy --all docker://$dst docker://ghcr.io/matheuscscp/${TARGET_REPOSITORY}:latest
      fi
      echo "image-with-digest=$dst" >> $GITHUB_OUTPUT
