# MIT License
#
# Copyright (c) 2023 Matheus Pimenta
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

inputs:
  component:
    required: true
  source-repository:
    required: true
  target-repository:
    required: true
  latest:
    required: false

outputs:
  image-with-digest:
    value: ${{ steps.copy.outputs.image-with-digest }}

runs:
  using: composite
  steps:
  - id: copy
    shell: bash
    env:
      COMPONENT: ${{ inputs.component }}
      SOURCE_REPOSITORY: ${{ inputs.source-repository }}
      TARGET_REPOSITORY: ${{ inputs.target-repository }}
      LATEST: ${{ inputs.latest }}
    run: |
      digest=$(cat ${COMPONENT}-digest.txt)
      src=ghcr.io/matheuscscp/gke-metadata-server/${SOURCE_REPOSITORY}@${digest}
      dst=ghcr.io/matheuscscp/${TARGET_REPOSITORY}@${digest}
      skopeo copy docker://$src docker://$dst
      skopeo copy docker://$dst docker://ghcr.io/matheuscscp/${TARGET_REPOSITORY}:$(yq .${COMPONENT} versions.yaml)
      if [ "$LATEST" != "skip" ]; then
        skopeo copy docker://$dst docker://ghcr.io/matheuscscp/${TARGET_REPOSITORY}:latest
      fi
      echo "image-with-digest=$dst" >> $GITHUB_OUTPUT
