# MIT License
#
# Copyright (c) 2023 Matheus Pimenta
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# This file is not only a core part of our test automation in this project,
# but also an example of how to configure Pods in a cluster where the emulator
# is deployed. Use this as reference for how to configure your production Pods.

# ServiceAccount configuration is the exact same of GKE Workload Identity.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: test-sa@gke-metadata-server.iam.gserviceaccount.com
---
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: default
spec:
  restartPolicy: Never

  # Use the ServiceAccount created above.
  serviceAccountName: test

  # These settings emulate the HTTP endpoint 169.254.169.254:80, hardcoded across
  # Google libraries as the endpoint for detecting if the code is running inside
  # a Google Cloud environment or not. The hostAliases field configures the DNS
  # entry. The init container adds the IP address to the loopback interface of
  # the Pod (this is why the NET_ADMIN security capability is required in this
  # init container). The sidecar container proxies TCP/IP connections on this
  # special endpoint to the NODE_IP:default_emulator_port network address, where
  # the emulator will be listening, on the same Kubernetes Node of this pod.
  hostAliases:
  - hostnames: [metadata.google.internal]
    ip: 169.254.169.254
  initContainers:
  - name: init-gke-metadata-proxy
    image: <GKE_METADATA_SERVER_IMAGE>
    imagePullPolicy: Always
    args: [init-network]
    securityContext:
      capabilities:
        add: [NET_ADMIN]
  containers:
  - name: gke-metadata-proxy
    image: <GKE_METADATA_SERVER_IMAGE>
    imagePullPolicy: Always
    args: [sidecar]
    env:
    - name: NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP

  # The containers below run our automatic tests. Replace them with your containers
  # in your production Pods.

  # This container demonstrates "GKE Workload Identity". The image does not have gcloud.
  # The tests running here perform authenticated operations in GCP by just communicating
  # with the well-known GCE/GKE Metadata APIs backed by the emulator. The custom APIs of
  # the emulator are also tested.
  - name: test
    image: <GKE_METADATA_SERVER_IMAGE>-test
    imagePullPolicy: Always
    env:
    - name: TEST_IMAGE
      value: <GKE_METADATA_SERVER_IMAGE>

  # This container demonstrates vanilla "Worload Identity Federation with Kubernetes".
  # The custom API of the emulator shown below returns a (non-secret) JSON with a
  # Google credential configuration, containiner the full name of the Workload Identity
  # Provider resource. The "gcloud auth login" command below configures the Pod with
  # the credentials that can be acquired by the parameters described inside this JSON
  # file. After performing login the container uses this authentication to make calls
  # to the GCS API via the gsutil binary from the Google CloudSDK image below. The
  # choice of gsutil here has meaning: gsutil does not work seamlessly with GKE's
  # native implementation of Workload Identity ("gcloud storage" does). This test
  # demonstrates how our Google Credential Configuration API allows gsutil to work
  # with Workload Identity. gsutil should not be used, though. Use "gcloud storage"
  # instead.
  - name: test-gcloud
    image: google/cloud-sdk:457.0.0-slim
    command: [/bin/bash]
    args:
    - -c
    - |
      set -ex

      METADATA_ENDPOINT="http://metadata.google.internal"
      CRED_CONFIG_API="/gkeMetadataEmulator/v1/pod/service-account/google-cred-config"
      curl -s -H "Metadata-Flavor: Emulator" "${METADATA_ENDPOINT}${CRED_CONFIG_API}?pretty" > creds.json
      cat creds.json
      gcloud auth login --cred-file=creds.json

      # upload a random object to gcs
      BUCKET="gke-metadata-server-test"
      while :; do
        key=$(openssl rand -hex 16)
        value=$(openssl rand -hex 16)
        echo -n $value > ./localfile.txt
        output=$(gsutil cp -n ./localfile.txt gs://${BUCKET}/${key} 2>&1)
        if [[ $output == *"Skipping existing item:"* ]]; then
          continue
        else
          break
        fi
      done

      # check if upload was successful
      if [ "$(gsutil cat gs://${BUCKET}/${key})" != "$value" ]; then
        echo "Error: Retrieved value does not match the expected value."
        gsutil rm gs://${BUCKET}/${key}
        exit 1
      fi
      echo "Retrieved value matches the expected value. Success!"
      gsutil rm gs://${BUCKET}/${key}
