# MIT License
#
# Copyright (c) 2023 Matheus Pimenta
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: test-sa@gke-metadata-server.iam.gserviceaccount.com
---
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: default
spec:
  serviceAccountName: test
  restartPolicy: Never
  hostAliases:
  - ip: 169.254.169.254
    hostnames: [metadata.google.internal]
  containers:
  - name: gke-metadata-proxy
    image: matheuscscp/gke-metadata-server:dev
    imagePullPolicy: Always
    args: [sidecar]
    env:
    - name: NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    securityContext:
      capabilities:
        add: [NET_ADMIN]
  - name: test-gcloud
    image: google/cloud-sdk:457.0.0-slim
    command: [/bin/sh]
    args:
    - -c
    - |
      set -x

      # test oauth 2.0 access token API
      curl -s -i -H "Metadata-Flavor: Google" "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token?pretty" > logs.txt 2>&1
      echo "" >> logs.txt

      # test id token token API
      curl -s -i -H "Metadata-Flavor: Google" "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?pretty&audience=test.com" >> logs.txt 2>&1
      echo "" >> logs.txt

      # test gcp creds config API
      curl -s -H "Metadata-Flavor: Emulator" "http://metadata.google.internal/gkeMetadataEmulator/v1/pod/service-account/google-cred-config?pretty" > creds.json 2>&1
      cat creds.json >> logs.txt
      gcloud auth login --cred-file=creds.json >> logs.txt 2>&1
      gsutil ls gs://gke-metadata-server-test >> logs.txt 2>&1

      cat logs.txt
  - name: test-go
    image: matheuscscp/gke-metadata-server:dev
    imagePullPolicy: Always
    args:
    - test-list-objects
    - --bucket=gke-metadata-server-test
