# Copyright 2025 Matheus Pimenta.
# SPDX-License-Identifier: AGPL-3.0

inputs:
  title:
    required: true
  message-file:
    required: true

runs:
  using: composite
  steps:
  - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
    env:
      TITLE: ${{ inputs.title }}
      MESSAGE_FILE: ${{ inputs.message-file }}
    with:
      script: |
        const { TITLE, MESSAGE_FILE } = process.env
        const commentIdentifier = TITLE + ':'
        const msg = require('fs').readFileSync(MESSAGE_FILE).toString().trim()

        const issue_number = context.issue.number
        const { owner, repo } = context.repo
        const body = commentIdentifier + '\n\n' + "```\n" + msg + "\n```"

        const { data: comments } = await github.rest.issues.listComments({
          issue_number,
          owner,
          repo,
        })
        const previousComment = comments.find(c => c.body.includes(commentIdentifier))
        if (previousComment) {
          await github.rest.issues.updateComment({
            comment_id: previousComment.id,
            owner,
            repo,
            body,
          })
        } else {
          await github.rest.issues.createComment({
            issue_number,
            owner,
            repo,
            body,
          })
        }
