# Copyright 2025 Matheus Pimenta.
# SPDX-License-Identifier: AGPL-3.0

inputs:
  version:
    required: false
  platforms:
    required: false
    default: linux/amd64

runs:
  using: composite

  steps:
  - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
  - uses: actions/setup-go@v6
    with:
      go-version: 1.26.0
      cache: false

  - run: make tidy
    shell: bash
  - name: Fail if make tidy produced changes
    shell: bash
    run: |
      if [ -n "$(git diff --name-only)" ] || [ -n "$(git status --porcelain | grep '??')" ]; then
        git status
        echo ""
        echo "The command 'make tidy' produced differences."
        echo "Please remember to run it locally before committing your changes."
        echo ""
        exit 1
      fi

  - name: Set version
    shell: bash
    env:
      VERSION: ${{ inputs.version }}
    run: |
      if [ "${VERSION}" = "" ]; then
        VERSION="100.0.0-ci"
      fi
      echo $VERSION > version.txt
  - run: make gen-ebpf ci-cluster build ci-test
    shell: bash
    env:
      PLATFORMS: ${{ inputs.platforms }}
