# Copyright 2025 Matheus Pimenta.
# SPDX-License-Identifier: AGPL-3.0

inputs:
  version:
    required: false
  platforms:
    required: false
    default: linux/amd64
  skip-tests:
    required: false

runs:
  using: composite

  steps:
  - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
  - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
    with:
      go-version: 1.26.0
      cache: false
  - name: Install cue
    shell: bash
    run: go install cuelang.org/go/cmd/cue@latest

  - run: make tidy
    shell: bash
  - name: Fail if make tidy produced changes
    shell: bash
    run: |
      if [ -n "$(git diff --name-only)" ] || [ -n "$(git status --porcelain | grep '??')" ]; then
        git status
        echo ""
        echo "The command 'make tidy' produced differences."
        echo "Please remember to run it locally before committing your changes."
        echo ""
        exit 1
      fi

  - name: Install eBPF toolchain
    shell: bash
    run: |
      sudo apt-get update && sudo apt-get install -y linux-tools-common linux-tools-generic libbpf-dev
      # Workaround: the runner kernel version may not match available linux-tools packages.
      # Symlink the generic tools directory so the bpftool wrapper can find it.
      TOOLS_DIR=$(ls -d /usr/lib/linux-tools/*-generic 2>/dev/null | head -1)
      if [ -n "$TOOLS_DIR" ] && [ ! -d "/usr/lib/linux-tools/$(uname -r)" ]; then
        sudo ln -s "$TOOLS_DIR" "/usr/lib/linux-tools/$(uname -r)"
      fi
  - name: Set version
    shell: bash
    env:
      VERSION: ${{ inputs.version }}
    run: |
      if [ "${VERSION}" = "" ]; then
        VERSION="100.0.0-ci"
      fi
      echo $VERSION > version.txt
  - run: |
      if [ "$SKIP_TESTS" = "true" ]; then
        make gen-ebpf build
      else
        make gen-ebpf ci-cluster build build-go-test ci-test
      fi
    shell: bash
    env:
      PLATFORMS: ${{ inputs.platforms }}
      SKIP_TESTS: ${{ inputs.skip-tests }}
