# Copyright 2025 Matheus Pimenta.
# SPDX-License-Identifier: AGPL-3.0

inputs:
  image:
    required: true

runs:
  using: composite
  steps:
  - run: |
      cosign sign --yes $image && cosign verify $image \
        --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
        --certificate-identity=https://github.com/matheuscscp/gke-metadata-server/.github/workflows/release.yml@refs/heads/main
    shell: bash
    env:
      image: ${{ inputs.image }}
