# MIT License
#
# Copyright (c) 2023 Matheus Pimenta
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

inputs:
  registry:
    required: true

runs:
  using: composite
  steps:
  - name: Setup image names
    run: |
      echo "CONTAINER_WITH_DIGEST=${image}@$(cat container-digest.txt)" >> $GITHUB_ENV
      echo "CONTAINER_WITH_TAG=${image}:$(cat container-version.txt)" >> $GITHUB_ENV
      echo "CONTAINER_WITH_TAG_LATEST=${image}:latest" >> $GITHUB_ENV
    shell: bash
    env:
      image: ${{ inputs.registry }}/matheuscscp/gke-metadata-server
  - name: Create tags for tested image
    run: |
      docker tag ghcr.io/matheuscscp/gke-metadata-server/test@$(cat container-digest.txt) $CONTAINER_WITH_TAG
      docker tag $CONTAINER_WITH_TAG $CONTAINER_WITH_TAG_LATEST
    shell: bash
  - run: docker push $CONTAINER_WITH_TAG && docker push $CONTAINER_WITH_TAG_LATEST
    shell: bash
  - run: cosign sign --yes $CONTAINER_WITH_DIGEST
    shell: bash
  - run: |
      cosign verify $CONTAINER_WITH_DIGEST \
        --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
        --certificate-identity=https://github.com/matheuscscp/gke-metadata-server/.github/workflows/release.yml@refs/heads/main
    shell: bash
