# Copyright 2025 Matheus Pimenta.
# SPDX-License-Identifier: AGPL-3.0

name: terraform-plan

on: [pull_request]

permissions: {}

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: terraform-plan
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
      with:
        project_id: gke-metadata-server
        workload_identity_provider: projects/637293746831/locations/global/workloadIdentityPools/github-actions/providers/github-actions
        service_account: tf-plan@gke-metadata-server.iam.gserviceaccount.com
    - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
    - run: cd terraform/ && terraform init && terraform plan -no-color > plan.txt
    - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        TITLE: Terraform Plan
        MESSAGE_FILE: terraform/plan.txt
      with:
        script: |
          const { TITLE, MESSAGE_FILE } = process.env
          const commentIdentifier = TITLE + ':'
          const msg = require('fs').readFileSync(MESSAGE_FILE).toString().trim()

          const issue_number = context.issue.number
          const { owner, repo } = context.repo
          const body = commentIdentifier + '\n\n' + "```\n" + msg + "\n```"

          const { data: comments } = await github.rest.issues.listComments({
            issue_number,
            owner,
            repo,
          })
          const previousComment = comments.find(c => c.body.includes(commentIdentifier))
          if (previousComment) {
            await github.rest.issues.updateComment({
              comment_id: previousComment.id,
              owner,
              repo,
              body,
            })
          } else {
            await github.rest.issues.createComment({
              issue_number,
              owner,
              repo,
              body,
            })
          }
